# -*- coding: utf-8 -*-
"""1.RPC_factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxAK3QWDnx2PLQEW443G1lN5BDhbJmk7
"""

#server code:
from xmlrpc.server import SimpleXMLRPCServer


def compute_factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * compute_factorial(n - 1)


server = SimpleXMLRPCServer(("localhost", 8000))
print("Server listening on port 8000...")
server.register_function(compute_factorial, "compute_factorial")
server.serve_forever()

#client code:
import xmlrpc.client

server = xmlrpc.client.ServerProxy("http://localhost:8000")

number = int(input("Enter an integer to compute its factorial: "))

result = server.compute_factorial(number)

print(f"The factorial of {number} is {result}")